workflows:
  ios-ipa-build:
    name: iOS IPA Build (Expo Ejected)
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: "com.avinash.KL-Connect"
        apple_id: "avinashdola0@gmail.com"
      xcode: latest
      vars:
        XCODE_WORKSPACE: "ios/YourApp.xcworkspace"
        XCODE_SCHEME: "YourApp"
    scripts:
      - name: Install Node modules
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build .ipa archive
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build//*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
